[package]
name = "ma_2_pdf"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.8.0"
shiva = {version="1.4.8", features= ["html", "markdown", "text", "csv", "rtf", "docx", "xml", "xls", "xlsx", "ods", "typst"]}
